version: 0.2

phases:
  install:
    commands:
      - git describe --tags --abbrev=0 HEAD
      - export LATEST_TAG=$(git describe --tags --abbrev=0 HEAD)
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Copying appspec.yml to build directory...
      - cp appspec.yml dist/ || echo "Failed to copy appspec.yml"  # Add error handling
      - echo Copying scripts directory to build directory...
      - cp -R scripts/ dist/ || echo "Failed to copy scripts directory"
artifacts:
  name: my-app-$LATEST_TAG
  files:
    - '**/*'  # Include all files from the build directory
  base-directory: dist  # React build output directory
  discard-paths: no  # Flatten directory structure